package enttenant

import (
	"context"
	"fmt"
	"reflect"
	"strings"

	"entgo.io/ent"

	"github.com/im10furry/saas"
	"github.com/im10furry/saas/core/types"
	"github.com/im10furry/saas/data"
)

// Mutation is the storage-level predicate surface generated by Ent mutations.
type Mutation interface {
	Op() ent.Op
	WhereP(...SelectorPredicate)
	Field(string) (ent.Value, bool)
	SetField(string, ent.Value) error
}

// MutationFilter applies tenant guards to Ent mutations.
type MutationFilter struct {
	config Config
}

// NewMutationFilter creates a reusable Ent mutation tenant filter.
func NewMutationFilter(config Config) MutationFilter {
	return MutationFilter{config: config.normalize()}
}

// FilterMutation applies tenant isolation to mutation using config.
func FilterMutation(ctx context.Context, mutation Mutation, config Config) error {
	return NewMutationFilter(config).Apply(ctx, mutation)
}

// Apply guards create mutations and appends tenant predicates to update/delete mutations.
func (filter MutationFilter) Apply(ctx context.Context, mutation Mutation) error {
	if mutation == nil {
		return ErrNilMutation
	}

	config := filter.config.normalize()
	dataFilter, err := data.NewFilter(ctx, config.filterOptions()...)
	if err != nil {
		return err
	}
	if dataFilter.IsHost() {
		return nil
	}

	tenantID, ok := dataFilter.TenantID()
	if !ok {
		return data.ErrNoTenant
	}

	op := mutation.Op()
	switch {
	case op.Is(ent.OpCreate):
		value, ok := mutation.Field(config.TenantField)
		if ok {
			if fmt.Sprint(value) != tenantID.String() {
				return saas.ErrTenantMismatch
			}
			return nil
		}
		if err := mutation.SetField(config.TenantField, tenantID.String()); err != nil {
			return fmt.Errorf("%w: %s: %v", ErrTenantFieldNotFound, config.TenantField, err)
		}
		return nil
	case op.Is(ent.OpUpdate), op.Is(ent.OpUpdateOne):
		if invalidTenantFieldUpdate(mutation, config.TenantField, tenantID.String()) {
			return ErrTenantFieldUpdate
		}
		mutation.WhereP(selectorPredicate(config, tenantID))
		return nil
	case op.Is(ent.OpDelete), op.Is(ent.OpDeleteOne):
		mutation.WhereP(selectorPredicate(config, tenantID))
		return nil
	default:
		return ErrUnsupportedMutation
	}
}

func invalidTenantFieldUpdate(mutation Mutation, tenantField, tenantID string) bool {
	fields := []string{tenantField}
	if index := strings.LastIndexByte(tenantField, '.'); index >= 0 {
		fields = append(fields, tenantField[index+1:])
	}
	matchedSet := false
	for _, field := range fields {
		if value, ok := mutation.Field(field); ok {
			if !tenantMutationValueMatches(value, tenantID) {
				return true
			}
			matchedSet = true
		}
	}

	type fieldsMutation interface{ Fields() []string }
	type addedFieldsMutation interface{ AddedFields() []string }
	type clearedFieldsMutation interface{ ClearedFields() []string }

	if mutation, ok := mutation.(fieldsMutation); ok {
		for _, changedField := range mutation.Fields() {
			if tenantMutationFieldMatches(changedField, fields) && !matchedSet {
				return true
			}
		}
	}
	if mutation, ok := mutation.(addedFieldsMutation); ok {
		for _, changedField := range mutation.AddedFields() {
			if tenantMutationFieldMatches(changedField, fields) {
				return true
			}
		}
	}
	if mutation, ok := mutation.(clearedFieldsMutation); ok {
		for _, changedField := range mutation.ClearedFields() {
			if tenantMutationFieldMatches(changedField, fields) {
				return true
			}
		}
	}
	return false
}

func tenantMutationValueMatches(value ent.Value, tenantID string) bool {
	reflected := reflect.ValueOf(value)
	for reflected.IsValid() && (reflected.Kind() == reflect.Pointer || reflected.Kind() == reflect.Interface) {
		if reflected.IsNil() {
			return false
		}
		reflected = reflected.Elem()
	}
	if !reflected.IsValid() {
		return false
	}
	stringType := reflect.TypeOf("")
	tenantIDType := reflect.TypeOf(types.TenantID(""))
	return (reflected.Type() == stringType || reflected.Type() == tenantIDType) && reflected.String() == tenantID
}

func tenantMutationFieldMatches(changed string, tenantFields []string) bool {
	for _, tenantField := range tenantFields {
		if strings.EqualFold(changed, tenantField) {
			return true
		}
	}
	return false
}

// Hook returns an Ent mutation hook that enforces tenant isolation before mutation execution.
func Hook(config Config) ent.Hook {
	filter := NewMutationFilter(config)
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, mutation ent.Mutation) (ent.Value, error) {
			scoped, ok := mutation.(Mutation)
			if !ok {
				return nil, ErrUnsupportedMutation
			}
			if err := filter.Apply(ctx, scoped); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, mutation)
		})
	}
}
