package enttenant

import (
	"context"

	"github.com/darkinno-tech/saas/data"
)

// Query is the storage-level predicate surface generated by Ent query builders.
type Query interface {
	WhereP(...SelectorPredicate)
}

// QueryFilter applies tenant predicates to Ent query builders.
type QueryFilter struct {
	config Config
}

// NewQueryFilter creates a reusable Ent query tenant filter.
func NewQueryFilter(config Config) QueryFilter {
	return QueryFilter{config: config.normalize()}
}

// FilterQuery applies tenant isolation to query using config.
func FilterQuery(ctx context.Context, query Query, config Config) error {
	return NewQueryFilter(config).Apply(ctx, query)
}

// Apply appends the current tenant predicate to query. Host contexts are left unchanged.
func (filter QueryFilter) Apply(ctx context.Context, query Query) error {
	if query == nil {
		return ErrNilQuery
	}

	config := filter.config.normalize()
	dataFilter, err := data.NewFilter(ctx, config.filterOptions()...)
	if err != nil {
		return err
	}
	if dataFilter.IsHost() {
		return nil
	}

	tenantID, ok := dataFilter.TenantID()
	if !ok {
		return data.ErrNoTenant
	}
	query.WhereP(selectorPredicate(config, tenantID))
	return nil
}
